Revert "mojo: Make shared message IDs strongly typed"
This reverts commit 0469e1d841fc110f13b8453b57e56bcb13cf7d2c.

Reason for revert: broke the build: https://ci.chromium.org/ui/p/chromium/builders/ci/android-x86-rel/64273/overview
gen/services/viz/public/mojom/compositing/compositor_frame_sink.mojom.cc:364:58: error: no member named 'kCompositorFrameSink_SubmitCompositorFrame_Name' in namespace 'viz::mojom::internal'

Original change's description:
> mojo: Make shared message IDs strongly typed
>
> This change changes Mojo's interface message IDs from
> generic `constexpr uint32_t` to interface specific enum classes.
>
> Design doc: http://go/predictive-mojo-allocation
>
> BUG=40278139
> TEST=Try jobs
>
> Change-Id: I4434ae6611ee947d18f40b7ea1e69cb45da8edc0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5353690
> Commit-Queue: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Yuzhu Shen <yzshen@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1272621}

Bug: 40278139
Change-Id: Ida1b9d3669047b605e96baa02c5a13942fd93eb8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5371095
Auto-Submit: Daniel Cheng <dcheng@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1272624}
NOKEYCHECK=True
GitOrigin-RevId: d753cf84e60fb06fae471e3919b1308867228e0b