Revert of Gets gn check to execute cleanly in mojo/common (patchset #4 id:60001 of https://codereview.chromium.org/1256593003/)
Reason for revert:
Caused failes on the windows gn bot: http://build.chromium.org/p/chromium.win/builders/Win8%20GN%20%28dbg%29/builds/10109/steps/compile/logs/stdio :
485/11287] CXX obj/ui/views/views/desktop_screen_win.obj
FAILED: E:/b/depot_tools/python276_bin/python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:ipc_mojo_unittests.exe /PDB:ipc_mojo_unittests.exe.pdb @ipc_mojo_unittests.exe.rsp
mojo.dll.lib(mojo.dll) : error LNK2005: "public: __thiscall mojo::common::HandleWatcher::HandleWatcher(void)" (??0HandleWatcher@common@mojo@@QAE@XZ) already defined in handle_watcher.obj

mojo.dll.lib(mojo.dll) : error LNK2005: "public: __thiscall mojo::common::HandleWatcher::~HandleWatcher(void)" (??1HandleWatcher@common@mojo@@QAE@XZ) already defined in handle_watcher.obj

mojo.dll.lib(mojo.dll) : error LNK2005: "public: void __thiscall mojo::common::HandleWatcher::Start(class mojo::Handle const &,unsigned int,unsigned __int64,class base::Callback<void __cdecl(unsigned int)> const &)" (?Start@HandleWatcher@common@mojo@@QAEXABVHandle@3@I_KABV?$Callback@$$A6AXI@Z@base@@@Z) already defined in handle_watcher.obj

ipc_mojo_unittests.exe : fatal error LNK1169: one or more multiply defined symbols found

Original issue's description:
> Gets gn check to execute cleanly in mojo/common
>
> This one is trickier. I'm changing mojo/common:common_base to be a
> source_set. Here's why. When I add the necessary deps, in particular
>     "//third_party/mojo/src/mojo/public/cpp/bindings:bindings",
> then I get link errors for the environment, eg
> gen/third_party/mojo/src/mojo/public/interfaces/bindings/interface_control_messages.mojom.cc:719: error: undefined reference to 'mojo::Environment::GetDefaultLogger()'
> These symbols are in //mojo/environment. If I add //mojo/environment
> to the list of deps for common_base I end up with a cycle as
> environment depends upon common_base. By changing to source_set
> common_base isn't linked and everyone is happy.
>
> As a result of this I had to consolidate //mojo/environment into a single source set.
>
> BUG=none
> TEST=none
> R=ben@chromium.org
>
> Committed: https://crrev.com/67b0a7be4ff751b1cf83be5af817a61ff7154aa8
> Cr-Commit-Position: refs/heads/master@{#340527}

TBR=ben@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=none

Review URL: https://codereview.chromium.org/1262503002

Cr-Original-Commit-Position: refs/heads/master@{#340584}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 393104d55ec70415c65049a83509f5d2a1ebac11