Try to kill hung apptests more reliably on Windows.
Use taskkill.exe instead of Popen.kill() on Windows.
Similar to many other Python [sub]process termination paths, eg:
  build/util/lib/common/util.py
  build/scripts/slave/kill_processes.py
  third_party/WebKit/Tools/Scripts/webkitpy/common/system/executive.py

On Chromium Mojo Windows mojo_apptests flakily hangs (see bug).
The thread running a test subprocess still won't join after calling Popen.kill():
  Error: Test hung and could not be killed!
This change should terminate the test subprocess more reliably on Win.

BUG=517661
TEST=Fewer cases of mojo_apptests timing out for failing to kill a hung apptests subprocess
R=dpranke@chromium.org
TBR=sky@chromium.org

Review URL: https://codereview.chromium.org/1392663002

Cr-Original-Commit-Position: refs/heads/master@{#352995}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 96f1d941e423744c65133419a09fdfdefa65cb81