Revert 258077 "Remove PrepareForShutdown"
Broke Linux official builder:
http://build.chromium.org/p/chromium/builders/Linux/builds/48352/steps/compile/logs/stdio

../../apps/shell/browser/shell_browser_main_parts.cc:197:42:error: 'class aura::WindowEventDispatcher' has no member named 'PrepareForShutdown'
ninja: build stopped: subcommand failed.

> Remove PrepareForShutdown
> Filter events after shutdown in event filter instead.
> 
> BUG=None
> 
> Review URL: https://codereview.chromium.org/196573023

TBR=oshima@chromium.org

Review URL: https://codereview.chromium.org/205313002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src/mojo@258103 0039d316-1c4b-4281-b951-d872f2087c98